/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URL;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.ImageIcon;
import monitordispositivos.AnalistaLocal;
import org.inspira.polivoto.AccionesConsultor;
import org.json.JSONException;
import polivoto.threading.IncommingRequestHandler;

/**
 *
 * @author David Vargas
 */
public class Acceso extends javax.swing.JFrame {

    public static AccionesConsultor AC;
    /**
     * Creates new form Results
     */
    private static LinkedList<String> titulos;

    public Acceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContacto = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBotonFacebook = new javax.swing.JButton();
        jBotonPaginaWeb = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jIP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButttonIngresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPwd = new javax.swing.JPasswordField();
        jFondo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPoliVoto = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jmContacto = new javax.swing.JMenuItem();

        setLocationRelativeTo(null);
        jContacto.setTitle("PoliVoto Electrónico");
        jContacto.setBackground(new java.awt.Color(255, 255, 255));
        jContacto.setMinimumSize(new java.awt.Dimension(437, 260));
        jContacto.setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/logo.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html> <h2>PoliVoto Electrónico &copy 2015</h2>  <p>Copia exclusiva para la Unidad Profesional <p>Interdisciplinaria en Ingenierías y Ciencias <p>Administrativas del Instituto Politécnico <p>Nacional. <p>Contacto y ayuda:</p>  <p>David A. Vargas: +52 (55) 2989 2764  <p>Juan Capiz: +52 (55) 1379 0281  <p>Alfonso De La Rosa: +52 (55) 4892 5376 <p>correo: contacto@votacionesipn.com</html>");

        jBotonFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/facebook.png"))); // NOI18N
        jBotonFacebook.setMaximumSize(new java.awt.Dimension(40, 40));
        jBotonFacebook.setMinimumSize(new java.awt.Dimension(40, 40));
        jBotonFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonFacebookActionPerformed(evt);
            }
        });

        jBotonPaginaWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/icono-web.png"))); // NOI18N
        jBotonPaginaWeb.setMaximumSize(new java.awt.Dimension(40, 40));
        jBotonPaginaWeb.setMinimumSize(new java.awt.Dimension(40, 40));
        jBotonPaginaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPaginaWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jContactoLayout = new javax.swing.GroupLayout(jContacto.getContentPane());
        jContacto.getContentPane().setLayout(jContactoLayout);
        jContactoLayout.setHorizontalGroup(
            jContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jContactoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jContactoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBotonFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        jContactoLayout.setVerticalGroup(
            jContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jContactoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar");
        setFocusable(false);
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icono.png")).getImage());
        setMinimumSize(new java.awt.Dimension(500, 521));
        setResizable(false);

        jPanel.setLayout(null);

        jIP.setBackground(new java.awt.Color(233, 142, 141));
        jIP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jIP.setForeground(new java.awt.Color(51, 51, 51));
        jIP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jIP.setText("192.168.1.82");
        jIP.setToolTipText("Ingrese la IP del servidor de aplicaciones");
        jIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIPKeyTyped(evt);
            }
        });
        jPanel.add(jIP);
        jIP.setBounds(150, 230, 200, 30);

        jLabel1.setText("Server");
        jPanel.add(jLabel1);
        jLabel1.setBounds(150, 210, 200, 16);

        jButttonIngresar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButttonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButttonIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButttonIngresar.setText("Ingresar");
        jButttonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButttonIngresarMouseClicked(evt);
            }
        });
        jPanel.add(jButttonIngresar);
        jButttonIngresar.setBounds(130, 349, 240, 30);

        jLabel2.setText("Contraseña");
        jPanel.add(jLabel2);
        jLabel2.setBounds(150, 280, 200, 16);

        jPwd.setBackground(new java.awt.Color(233, 142, 141));
        jPwd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPwd.setForeground(new java.awt.Color(51, 51, 51));
        jPwd.setText("upiita");
        jPwd.setToolTipText("Contraseña");
        jPwd.setMaximumSize(new java.awt.Dimension(6, 20));
        jPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPwdKeyTyped(evt);
            }
        });
        jPanel.add(jPwd);
        jPwd.setBounds(150, 300, 200, 30);

        jFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/background.png"))); // NOI18N
        jFondo.setFocusCycleRoot(true);
        jPanel.add(jFondo);
        jFondo.setBounds(0, 0, 500, 500);

        jMenuPoliVoto.setText("PoliVoto Electrónico");

        jmItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        jMenuPoliVoto.add(jmItemSalir);

        jMenuBar.add(jMenuPoliVoto);

        jMenuAyuda.setText("Ayuda");

        jmContacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jmContacto.setText("Contacto");
        jmContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmContactoActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jmContacto);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButttonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButttonIngresarMouseClicked
        String host = jIP.getText();
        String pwd = jPwd.getText();
        if (connect(host, pwd)) {
            continuar();
        }
    }//GEN-LAST:event_jButttonIngresarMouseClicked

    private void jPwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwdKeyTyped

        char c = evt.getKeyChar();
        if (c == '\n') {
            String host = jIP.getText();
            String pwd = jPwd.getText();
            if (connect(host, pwd)) {
                continuar();
            }
        }

    }//GEN-LAST:event_jPwdKeyTyped

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContactoActionPerformed
        jContacto.setVisible(true);
    }//GEN-LAST:event_jmContactoActionPerformed

    private void jBotonFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonFacebookActionPerformed

        try {
            Desktop.getDesktop().browse(new URL("http://www.facebook.com/votacionesIPN").toURI());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jBotonFacebookActionPerformed

    private void jBotonPaginaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPaginaWebActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("http://www.votacionesipn.com").toURI());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jBotonPaginaWebActionPerformed

    private void jIPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIPKeyTyped
        char c = evt.getKeyChar();
        if (c == '\n') {
            jPwd.setFocusable(true);
        }
        if (!Character.isDigit(c) && c != '.') {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jIPKeyTyped

    private void continuar() {
        
        AnalistaLocal analistaLocal = new AnalistaLocal();
        analistaLocal.init();
        analistaLocal.beginListening();
        dispose();
        
        /** 
         * Following piece of code prepares the last views
         *
         **/
//        for (int i = 0; i < AC.getPreguntas().length(); i++) {
//            LogIn consultor = new LogIn(this, (i + 1));
//            consultor.iniciar();
//        }
    }

    private boolean connect(String host, String pwd) {
        return logear_como_Consultor(host, pwd);
    }

    private boolean logear_como_Consultor(String host, String pwd) {
        boolean success = false;
        try {
            AC = new AccionesConsultor(host, pwd);
            AC.consultaPreguntas();
            success = true;
            new IncommingRequestHandler().start(); // We need to keep track of this object.
        } catch (IOException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadPaddingException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        }
        return success;
    }
    /**
     * @param args the command line arguments
     */
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonFacebook;
    private javax.swing.JButton jBotonPaginaWeb;
    private javax.swing.JLabel jButttonIngresar;
    private javax.swing.JDialog jContacto;
    private javax.swing.JLabel jFondo;
    private javax.swing.JTextField jIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPoliVoto;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPwd;
    private javax.swing.JMenuItem jmContacto;
    private javax.swing.JMenuItem jmItemSalir;
    // End of variables declaration//GEN-END:variables

}