package InterfazUsuario;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.inspira.polivoto.AccionesConsultor;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author David Azaraf Vargas Baza e-mail: aza.369@gmail.com Instituto
 * Politecnico Nacional, Mexico 2014
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    private final int frameId;
    private final LinkedList<JPanel> PanelesName = new LinkedList<>();
    private final LinkedList<JPanel> PanelesNumb = new LinkedList<>();
    private final LinkedList<JLabel> EtiquetastxtOpcName = new LinkedList<>();
    private final LinkedList<JLabel> EtiquetastxtOpcNumb = new LinkedList<>();
    private final LinkedList<Color> colores = new LinkedList<>();
    private AccionesConsultor accionesConsultor;

    public void setAccionesConsultor(AccionesConsultor accionesConsultor) {
        this.accionesConsultor = accionesConsultor;
    }

    public LogIn(int frameId) {
        this.frameId = frameId;
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SelEscuela = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonSelectEscuela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelEncabezado4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jHoraTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelGrafica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelEstadisticas = new javax.swing.JPanel();
        panelTotal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelNumTotal = new javax.swing.JPanel();
        resultadoSuma = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PanelOpcion1 = new javax.swing.JPanel();
        txtOpc1 = new javax.swing.JLabel();
        PanelNumOpcion1 = new javax.swing.JPanel();
        txtOpcNum1 = new javax.swing.JLabel();
        PanelOpcion2 = new javax.swing.JPanel();
        txtOpc2 = new javax.swing.JLabel();
        PanelNumOpcion2 = new javax.swing.JPanel();
        txtOpcNum2 = new javax.swing.JLabel();
        PanelOpcion3 = new javax.swing.JPanel();
        txtOpc3 = new javax.swing.JLabel();
        PanelNumOpcion3 = new javax.swing.JPanel();
        txtOpcNum3 = new javax.swing.JLabel();
        PanelOpcion4 = new javax.swing.JPanel();
        txtOpc4 = new javax.swing.JLabel();
        PanelNumOpcion4 = new javax.swing.JPanel();
        txtOpcNum4 = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        PanelOpcion5 = new javax.swing.JPanel();
        txtOpc5 = new javax.swing.JLabel();
        PanelNumOpcion5 = new javax.swing.JPanel();
        txtOpcNum5 = new javax.swing.JLabel();
        PanelOpcion6 = new javax.swing.JPanel();
        txtOpc6 = new javax.swing.JLabel();
        PanelNumOpcion6 = new javax.swing.JPanel();
        txtOpcNum6 = new javax.swing.JLabel();
        PanelOpcion7 = new javax.swing.JPanel();
        txtOpc7 = new javax.swing.JLabel();
        PanelNumOpcion7 = new javax.swing.JPanel();
        txtOpcNum7 = new javax.swing.JLabel();
        PanelOpcion8 = new javax.swing.JPanel();
        txtOpc8 = new javax.swing.JLabel();
        PanelNumOpcion8 = new javax.swing.JPanel();
        txtOpcNum8 = new javax.swing.JLabel();
        PanelOpcion9 = new javax.swing.JPanel();
        txtOpc9 = new javax.swing.JLabel();
        PanelNumOpcion9 = new javax.swing.JPanel();
        txtOpcNum9 = new javax.swing.JLabel();
        PanelOpcion0 = new javax.swing.JPanel();
        txtOpc0 = new javax.swing.JLabel();
        PanelNumOpcion0 = new javax.swing.JPanel();
        txtOpcNum0 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        SelEscuela.setMinimumSize(new java.awt.Dimension(400, 300));
        SelEscuela.setResizable(false);
        SelEscuela.getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CECyT 1", "CECyT 2", "CECyT 3", "CECyT 4", "CECyT 5", "CECyT 6", "CECyT 7", "CECyT 8", "CECyT 9", "CECyT 10", "CECyT 11", "CECyT 12", "CECyT 13", "CECyT 14", "CECyT 15", "CECyT 16", "CET 1", "CICS UMA", "CICS UST", "ENCB", "ENMH", "ESCA", "ESCOM", "ESE", "ESEO", "ESFM", "ESIA", "ESIME", "ESIQIE", "ESIT", "ESM", "EST", "UPIBI", "UPIICSA", "UPIIG", "UPIITA", "UPIIZ" }));
        SelEscuela.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 160, 180, 40);

        jButtonSelectEscuela.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButtonSelectEscuela.setText("OK");
        jButtonSelectEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectEscuelaActionPerformed(evt);
            }
        });
        SelEscuela.getContentPane().add(jButtonSelectEscuela);
        jButtonSelectEscuela.setBounds(150, 240, 38, 34);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione su unidad");
        SelEscuela.getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 110, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/select.png"))); // NOI18N
        SelEscuela.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 310);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultor PoliVoto");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icono.png")).getImage());
        setMaximumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);

        panelEncabezado4.setBackground(new java.awt.Color(134, 36, 31));
        panelEncabezado4.setAlignmentX(1.0F);
        panelEncabezado4.setAlignmentY(1.0F);
        panelEncabezado4.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 11, 36);
        panelEncabezado4.add(jButton1, gridBagConstraints);

        jHoraTxt.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jHoraTxt.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 3.7;
        gridBagConstraints.insets = new java.awt.Insets(14, 2, 0, 0);
        panelEncabezado4.add(jHoraTxt, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/escudoBlanco.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 11, 10);
        panelEncabezado4.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/Escudos IPN/UPIITA.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 16, 0);
        panelEncabezado4.add(jLabel5, gridBagConstraints);

        panelGrafica.setBackground(new java.awt.Color(134, 36, 31));
        panelGrafica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelGrafica.setMaximumSize(new java.awt.Dimension(906, 494));
        panelGrafica.setMinimumSize(new java.awt.Dimension(906, 494));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        panelEstadisticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEstadisticas.setMaximumSize(new java.awt.Dimension(212, 582));
        panelEstadisticas.setMinimumSize(new java.awt.Dimension(212, 582));

        panelTotal.setBackground(new java.awt.Color(255, 255, 255));
        panelTotal.setMaximumSize(new java.awt.Dimension(101, 53));
        panelTotal.setMinimumSize(new java.awt.Dimension(101, 53));

        jLabel6.setBackground(new java.awt.Color(1, 1, 1));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Total:");

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNumTotal.setBackground(new java.awt.Color(255, 255, 255));
        panelNumTotal.setMaximumSize(new java.awt.Dimension(93, 53));
        panelNumTotal.setMinimumSize(new java.awt.Dimension(93, 53));

        resultadoSuma.setBackground(new java.awt.Color(1, 1, 1));
        resultadoSuma.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        resultadoSuma.setForeground(new java.awt.Color(1, 1, 1));
        resultadoSuma.setText("0");

        javax.swing.GroupLayout panelNumTotalLayout = new javax.swing.GroupLayout(panelNumTotal);
        panelNumTotal.setLayout(panelNumTotalLayout);
        panelNumTotalLayout.setHorizontalGroup(
            panelNumTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultadoSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNumTotalLayout.setVerticalGroup(
            panelNumTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultadoSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOpcion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpc1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOpcion1Layout = new javax.swing.GroupLayout(PanelOpcion1);
        PanelOpcion1.setLayout(PanelOpcion1Layout);
        PanelOpcion1Layout.setHorizontalGroup(
            PanelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion1Layout.setVerticalGroup(
            PanelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtOpc1.getAccessibleContext().setAccessibleName("txtOpc1");

        PanelNumOpcion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum1.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcNum1.setText("0");

        javax.swing.GroupLayout PanelNumOpcion1Layout = new javax.swing.GroupLayout(PanelNumOpcion1);
        PanelNumOpcion1.setLayout(PanelNumOpcion1Layout);
        PanelNumOpcion1Layout.setHorizontalGroup(
            PanelNumOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        PanelNumOpcion1Layout.setVerticalGroup(
            PanelNumOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        PanelOpcion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout PanelOpcion2Layout = new javax.swing.GroupLayout(PanelOpcion2);
        PanelOpcion2.setLayout(PanelOpcion2Layout);
        PanelOpcion2Layout.setHorizontalGroup(
            PanelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion2Layout.setVerticalGroup(
            PanelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum2.setText("0");

        javax.swing.GroupLayout PanelNumOpcion2Layout = new javax.swing.GroupLayout(PanelNumOpcion2);
        PanelNumOpcion2.setLayout(PanelNumOpcion2Layout);
        PanelNumOpcion2Layout.setHorizontalGroup(
            PanelNumOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelNumOpcion2Layout.setVerticalGroup(
            PanelNumOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        PanelOpcion3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpc3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOpcion3Layout = new javax.swing.GroupLayout(PanelOpcion3);
        PanelOpcion3.setLayout(PanelOpcion3Layout);
        PanelOpcion3Layout.setHorizontalGroup(
            PanelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion3Layout.setVerticalGroup(
            PanelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum3.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcNum3.setText("0");

        javax.swing.GroupLayout PanelNumOpcion3Layout = new javax.swing.GroupLayout(PanelNumOpcion3);
        PanelNumOpcion3.setLayout(PanelNumOpcion3Layout);
        PanelNumOpcion3Layout.setHorizontalGroup(
            PanelNumOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelNumOpcion3Layout.setVerticalGroup(
            PanelNumOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        PanelOpcion4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout PanelOpcion4Layout = new javax.swing.GroupLayout(PanelOpcion4);
        PanelOpcion4.setLayout(PanelOpcion4Layout);
        PanelOpcion4Layout.setHorizontalGroup(
            PanelOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion4Layout.setVerticalGroup(
            PanelOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum4.setText("0");

        javax.swing.GroupLayout PanelNumOpcion4Layout = new javax.swing.GroupLayout(PanelNumOpcion4);
        PanelNumOpcion4.setLayout(PanelNumOpcion4Layout);
        PanelNumOpcion4Layout.setHorizontalGroup(
            PanelNumOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumOpcion4Layout.createSequentialGroup()
                .addComponent(txtOpcNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelNumOpcion4Layout.setVerticalGroup(
            PanelNumOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        Creditos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Creditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creditos.setText("<html><i><b>PoliVoto Electrónico(c)</b><p>Instituto Politécnico Nacional<p>Octubre 2015</i><p><b><font color=\"blue\">www.votacionesipn.com</b></font></html>");
        Creditos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Creditos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        PanelOpcion5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpc5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOpcion5Layout = new javax.swing.GroupLayout(PanelOpcion5);
        PanelOpcion5.setLayout(PanelOpcion5Layout);
        PanelOpcion5Layout.setHorizontalGroup(
            PanelOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion5Layout.setVerticalGroup(
            PanelOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum5.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcNum5.setText("0");

        javax.swing.GroupLayout PanelNumOpcion5Layout = new javax.swing.GroupLayout(PanelNumOpcion5);
        PanelNumOpcion5.setLayout(PanelNumOpcion5Layout);
        PanelNumOpcion5Layout.setHorizontalGroup(
            PanelNumOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        PanelNumOpcion5Layout.setVerticalGroup(
            PanelNumOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        PanelOpcion6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout PanelOpcion6Layout = new javax.swing.GroupLayout(PanelOpcion6);
        PanelOpcion6.setLayout(PanelOpcion6Layout);
        PanelOpcion6Layout.setHorizontalGroup(
            PanelOpcion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion6Layout.setVerticalGroup(
            PanelOpcion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum6.setText("0");

        javax.swing.GroupLayout PanelNumOpcion6Layout = new javax.swing.GroupLayout(PanelNumOpcion6);
        PanelNumOpcion6.setLayout(PanelNumOpcion6Layout);
        PanelNumOpcion6Layout.setHorizontalGroup(
            PanelNumOpcion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelNumOpcion6Layout.setVerticalGroup(
            PanelNumOpcion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        PanelOpcion7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpc7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOpcion7Layout = new javax.swing.GroupLayout(PanelOpcion7);
        PanelOpcion7.setLayout(PanelOpcion7Layout);
        PanelOpcion7Layout.setHorizontalGroup(
            PanelOpcion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion7Layout.setVerticalGroup(
            PanelOpcion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum7.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcNum7.setText("0");

        javax.swing.GroupLayout PanelNumOpcion7Layout = new javax.swing.GroupLayout(PanelNumOpcion7);
        PanelNumOpcion7.setLayout(PanelNumOpcion7Layout);
        PanelNumOpcion7Layout.setHorizontalGroup(
            PanelNumOpcion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelNumOpcion7Layout.setVerticalGroup(
            PanelNumOpcion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        PanelOpcion8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout PanelOpcion8Layout = new javax.swing.GroupLayout(PanelOpcion8);
        PanelOpcion8.setLayout(PanelOpcion8Layout);
        PanelOpcion8Layout.setHorizontalGroup(
            PanelOpcion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion8Layout.setVerticalGroup(
            PanelOpcion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum8.setText("0");

        javax.swing.GroupLayout PanelNumOpcion8Layout = new javax.swing.GroupLayout(PanelNumOpcion8);
        PanelNumOpcion8.setLayout(PanelNumOpcion8Layout);
        PanelNumOpcion8Layout.setHorizontalGroup(
            PanelNumOpcion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumOpcion8Layout.createSequentialGroup()
                .addComponent(txtOpcNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelNumOpcion8Layout.setVerticalGroup(
            PanelNumOpcion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        PanelOpcion9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpc9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOpcion9Layout = new javax.swing.GroupLayout(PanelOpcion9);
        PanelOpcion9.setLayout(PanelOpcion9Layout);
        PanelOpcion9Layout.setHorizontalGroup(
            PanelOpcion9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion9Layout.setVerticalGroup(
            PanelOpcion9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum9.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcNum9.setText("0");

        javax.swing.GroupLayout PanelNumOpcion9Layout = new javax.swing.GroupLayout(PanelNumOpcion9);
        PanelNumOpcion9.setLayout(PanelNumOpcion9Layout);
        PanelNumOpcion9Layout.setHorizontalGroup(
            PanelNumOpcion9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum9, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        PanelNumOpcion9Layout.setVerticalGroup(
            PanelNumOpcion9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        PanelOpcion0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpc0.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout PanelOpcion0Layout = new javax.swing.GroupLayout(PanelOpcion0);
        PanelOpcion0.setLayout(PanelOpcion0Layout);
        PanelOpcion0Layout.setHorizontalGroup(
            PanelOpcion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcion0Layout.setVerticalGroup(
            PanelOpcion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpc0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelNumOpcion0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOpcNum0.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtOpcNum0.setText("0");

        javax.swing.GroupLayout PanelNumOpcion0Layout = new javax.swing.GroupLayout(PanelNumOpcion0);
        PanelNumOpcion0.setLayout(PanelNumOpcion0Layout);
        PanelNumOpcion0Layout.setHorizontalGroup(
            PanelNumOpcion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumOpcion0Layout.createSequentialGroup()
                .addComponent(txtOpcNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelNumOpcion0Layout.setVerticalGroup(
            PanelNumOpcion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOpcNum0, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelEstadisticasLayout = new javax.swing.GroupLayout(panelEstadisticas);
        panelEstadisticas.setLayout(panelEstadisticasLayout);
        panelEstadisticasLayout.setHorizontalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadisticasLayout.createSequentialGroup()
                        .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelOpcion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelOpcion0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelNumOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelNumOpcion8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelNumOpcion5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelNumOpcion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelNumOpcion0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Creditos)
                    .addGroup(panelEstadisticasLayout.createSequentialGroup()
                        .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNumTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadisticasLayout.createSequentialGroup()
                .addGap(0, 153, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        panelEstadisticasLayout.setVerticalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcion0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumOpcion0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNumTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEncabezado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectEscuelaActionPerformed
        SelEscuela.setVisible(false);
//        panelActualizacion4.setVisible(false);
//        logoEscuelaIMG4.setVisible(true);
        ImageIcon Img = new ImageIcon(getClass().getResource("/InterfazUsuario/imagenes/Escudos IPN/" + jComboBox1.getSelectedItem().toString() + ".png"));
//        logoEscuelaIMG4.setIcon(Img);
    }//GEN-LAST:event_jButtonSelectEscuelaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        try {
//            System.out.println("I'm frame " + frameId + " and my question is: " +
//                    accionesConsultor.getPreguntas().getJSONObject(frameId-1).getString("pregunta"));
//        } catch (JSONException ex) {
//            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
//        }
        prepararTabla();
        pedir_Datos();
        //pedir_Datos_Prueba();
        PieDataset dataset = crearDataset();
        JFreeChart chart = null;
        try {
            chart = createChart(dataset, accionesConsultor.getPreguntas().getJSONObject(frameId - 1).getString("pregunta"));
        } catch (JSONException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        ChartPanel pastel = new ChartPanel(chart);
        pastel.setBounds(panelGrafica.getVisibleRect());

        int y = 0;
        try {
            for (int x = 0; x < accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").length(); x++) {
                try {
                    if (accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(x).getString("reactivo").equals("Anular mi voto")) {
                        PanelesName.getLast().setVisible(true);
                        PanelesNumb.getLast().setVisible(true);
                        PanelesName.getLast().setBackground(Color.lightGray);
                        PanelesNumb.getLast().setBackground(Color.lightGray);
                        EtiquetastxtOpcName.getLast().setText("Nulo");
                        EtiquetastxtOpcNumb.getLast().setText("<html>" + accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(x).getInt("cantidad") + "</html>");
                        y = 1;
                    } else {
                        PanelesName.get(x - y).setVisible(true);
                        PanelesNumb.get(x - y).setVisible(true);
                        PanelesName.get(x - y).setBackground(colores.get(x - y));
                        PanelesNumb.get(x - y).setBackground(colores.get(x - y));
                        EtiquetastxtOpcName.get(x - y).setText("<html>" + accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(x).getString("reactivo") + "</html>");
                        EtiquetastxtOpcNumb.get(x - y).setText("<html>" + accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(x).getInt("cantidad") + "</html>");

                    }
                } catch (JSONException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (JSONException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            resultadoSuma.setText(Integer.toString(accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getInt("participantes")));
        } catch (JSONException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }

        panelGrafica.removeAll();
        panelGrafica.add(pastel);
        panelGrafica.repaint();
        //        panelActualizacion4.setVisible(true);

        jHoraTxt.setText("<html>Última actualización: " + askDate() + "</html>");
    }//GEN-LAST:event_jButton1ActionPerformed

    public String askDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private void pedir_Datos() {
        accionesConsultor.consultaConteoOpciones();
    }

    private PieDataset crearDataset() {
        DefaultPieDataset datos = new DefaultPieDataset();
        try {
            if (accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getInt("participantes") == 0) {
                datos.setValue("Sin datos", 0);
            } else {
                for (int i = 0; i < accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").length(); i++) {
                    int p = accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(i).getInt("cantidad");
                    if (accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(i).getString("reactivo").equals("Anular mi voto")) {
                        //System.out.println(Conteos.get(i)+ "*100/"+total +"=");
                        datos.setValue("Nulo", p);
                    } else {
                        //System.out.println(Conteos.get(i)+ "*100/"+total +"="+ ((Conteos.get(i)*100)/total));
                        datos.setValue(accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(i).getString("reactivo"), p);
                    }
                }
            }
        } catch (JSONException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        return datos;
    }

    private JFreeChart createChart(final PieDataset dataset, String title) {
        System.out.println("el titulo es aqui: " + title);
        JFreeChart chart = ChartFactory.createPieChart3D(
                title, // chart title
                dataset, // datos
                false, // incluir leyenda
                true, // tooltips
                false //url
        );
        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.ANTICLOCKWISE);
        plot.setForegroundAlpha(0.5f);

        plot.setNoDataMessage("Aún no hay votos");
        try {
            if (accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getInt("participantes") != 0) {
                int j = 0;
                for (int i = 0; i < accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").length(); i++) {
                    try {
                        if (accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(i).getString("reactivo").equals("Anular mi voto")) {
                            plot.setSectionPaint("Nulo", Color.lightGray);
                        } else {
                            plot.setSectionPaint(accionesConsultor.getConteoOpcionesPregunta().getJSONObject(frameId - 1).getJSONArray("conteo").getJSONObject(i).getString("reactivo"), colores.get(j));
                            j++;
                        }
                    } catch (JSONException ex) {
                        Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
//        else{
//            plot.setSectionPaint("No hay votos", Color.white);
//        }
        } catch (JSONException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }

        plot.setSimpleLabels(true);
        //plot.setBackgroundPaint(Color.white);
        plot.setBackgroundPaint(new GradientPaint(0, 0, Color.white, 0, 1000, new java.awt.Color(147, 60, 45)));

        PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                "{0}: {2} de votos", new DecimalFormat("0"), new DecimalFormat("0.0000%"));
        plot.setLabelGenerator(gen);
        final Rotator rotator = new Rotator(plot);
        rotator.start();

        return chart;

    }

    private void createPanelesNombre() {
        PanelesName.add(PanelOpcion1);
        PanelesName.add(PanelOpcion2);
        PanelesName.add(PanelOpcion3);
        PanelesName.add(PanelOpcion4);
        PanelesName.add(PanelOpcion5);
        PanelesName.add(PanelOpcion6);
        PanelesName.add(PanelOpcion7);
        PanelesName.add(PanelOpcion8);
        PanelesName.add(PanelOpcion9);
        PanelesName.add(PanelOpcion0);
    }

    private void createPanelesNumero() {
        PanelesNumb.add(PanelNumOpcion1);
        PanelesNumb.add(PanelNumOpcion2);
        PanelesNumb.add(PanelNumOpcion3);
        PanelesNumb.add(PanelNumOpcion4);
        PanelesNumb.add(PanelNumOpcion5);
        PanelesNumb.add(PanelNumOpcion6);
        PanelesNumb.add(PanelNumOpcion7);
        PanelesNumb.add(PanelNumOpcion8);
        PanelesNumb.add(PanelNumOpcion9);
        PanelesNumb.add(PanelNumOpcion0);
    }

    private void createTxtNombre() {
        EtiquetastxtOpcName.add(txtOpc1);
        EtiquetastxtOpcName.add(txtOpc2);
        EtiquetastxtOpcName.add(txtOpc3);
        EtiquetastxtOpcName.add(txtOpc4);
        EtiquetastxtOpcName.add(txtOpc5);
        EtiquetastxtOpcName.add(txtOpc6);
        EtiquetastxtOpcName.add(txtOpc7);
        EtiquetastxtOpcName.add(txtOpc8);
        EtiquetastxtOpcName.add(txtOpc9);
        EtiquetastxtOpcName.add(txtOpc0);
    }

    private void createTxtNumero() {
        EtiquetastxtOpcNumb.add(txtOpcNum1);
        EtiquetastxtOpcNumb.add(txtOpcNum2);
        EtiquetastxtOpcNumb.add(txtOpcNum3);
        EtiquetastxtOpcNumb.add(txtOpcNum4);
        EtiquetastxtOpcNumb.add(txtOpcNum5);
        EtiquetastxtOpcNumb.add(txtOpcNum6);
        EtiquetastxtOpcNumb.add(txtOpcNum7);
        EtiquetastxtOpcNumb.add(txtOpcNum8);
        EtiquetastxtOpcNumb.add(txtOpcNum9);
        EtiquetastxtOpcNumb.add(txtOpcNum0);
    }

    private void prepararTabla() {
        createPanelesNombre();
        createPanelesNumero();
        createTxtNombre();
        createTxtNumero();
        colores.add(Color.red);
        colores.add(Color.green);
        colores.add(Color.blue);
        colores.add(Color.yellow);
        colores.add(Color.magenta);
        colores.add(Color.cyan);
        colores.add(Color.pink);
        colores.add(Color.orange);
        colores.add(Color.darkGray);
        colores.add(Color.white);

        ListIterator<JPanel> i = PanelesName.listIterator();
        ListIterator<JPanel> j = PanelesNumb.listIterator();
        ListIterator<JLabel> k = EtiquetastxtOpcName.listIterator();
        ListIterator<JLabel> l = EtiquetastxtOpcNumb.listIterator();

        while (i.hasNext()) {
            i.next().setVisible(false);
        }
        while (j.hasNext()) {
            j.next().setVisible(false);
        }
        while (k.hasNext()) {
            k.next().setText(null);
        }
        while (l.hasNext()) {
            l.next().setText(null);
        }
    }

    public static BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    private int getFrameId() {
        return frameId;
    }

    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                LogIn.this.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creditos;
    private javax.swing.JPanel PanelNumOpcion0;
    private javax.swing.JPanel PanelNumOpcion1;
    private javax.swing.JPanel PanelNumOpcion2;
    private javax.swing.JPanel PanelNumOpcion3;
    private javax.swing.JPanel PanelNumOpcion4;
    private javax.swing.JPanel PanelNumOpcion5;
    private javax.swing.JPanel PanelNumOpcion6;
    private javax.swing.JPanel PanelNumOpcion7;
    private javax.swing.JPanel PanelNumOpcion8;
    private javax.swing.JPanel PanelNumOpcion9;
    private javax.swing.JPanel PanelOpcion0;
    private javax.swing.JPanel PanelOpcion1;
    private javax.swing.JPanel PanelOpcion2;
    private javax.swing.JPanel PanelOpcion3;
    private javax.swing.JPanel PanelOpcion4;
    private javax.swing.JPanel PanelOpcion5;
    private javax.swing.JPanel PanelOpcion6;
    private javax.swing.JPanel PanelOpcion7;
    private javax.swing.JPanel PanelOpcion8;
    private javax.swing.JPanel PanelOpcion9;
    private javax.swing.JFrame SelEscuela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSelectEscuela;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jHoraTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelEncabezado4;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JPanel panelNumTotal;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JLabel resultadoSuma;
    private javax.swing.JLabel txtOpc0;
    private javax.swing.JLabel txtOpc1;
    private javax.swing.JLabel txtOpc2;
    private javax.swing.JLabel txtOpc3;
    private javax.swing.JLabel txtOpc4;
    private javax.swing.JLabel txtOpc5;
    private javax.swing.JLabel txtOpc6;
    private javax.swing.JLabel txtOpc7;
    private javax.swing.JLabel txtOpc8;
    private javax.swing.JLabel txtOpc9;
    private javax.swing.JLabel txtOpcNum0;
    private javax.swing.JLabel txtOpcNum1;
    private javax.swing.JLabel txtOpcNum2;
    private javax.swing.JLabel txtOpcNum3;
    private javax.swing.JLabel txtOpcNum4;
    private javax.swing.JLabel txtOpcNum5;
    private javax.swing.JLabel txtOpcNum6;
    private javax.swing.JLabel txtOpcNum7;
    private javax.swing.JLabel txtOpcNum8;
    private javax.swing.JLabel txtOpcNum9;
    // End of variables declaration//GEN-END:variables
}
